---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
  - name: quotes-service
  - name: resource-version

outputs:
  - name: build

run:
  path: "quotes-service/ci/scripts/package.sh"
  args: [resource-version/number]
